[project]
name = "mcp-observability-demo"
version = "0.1.0"
description = "MCP observability demo: separate FastMCP tools and feedback servers with Langfuse tracing"
readme = "README.md"
authors = [ { name = "Windsurf Demo" } ]
requires-python = ">=3.10"

# Core runtime dependencies
dependencies = [
  "fastapi>=0.111",
  "starlette>=0.37",
  "uvicorn[standard]>=0.30",
  "fastmcp>=2.10",
  "langfuse>=2.0.0",
  "redis>=5.0",
  # Simple local client for testing MCP HTTP servers
  "mcp>=1.1.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

