version: 1.2.1
cache: true

# Registration and Interface
registration:
  socialLogins: []
  allowedDomains: []

interface:
  privacyPolicy:
    externalUrl: ""
    openNewTab: false
  termsOfService:
    externalUrl: ""
    openNewTab: false

# File Configuration
fileConfig:
  endpoints:
    assistants:
      fileLimit: 5
      fileSizeLimit: 10
      totalSizeLimit: 50
      supportedMimeTypes:
        - "image/.*"
        - "application/pdf"
    openAI:
      disabled: false
      fileLimit: 5
      fileSizeLimit: 10
      totalSizeLimit: 50
      supportedMimeTypes:
        - "image/.*"
        - "application/pdf"
    default:
      totalSizeLimit: 20

# Model Configurations
endpoints:
  # OpenAI configuration
  openAI:
    # Users provide their own key in the UI
    apiKey: "user_provided"
    models:
      default: 
        - "gpt-4-turbo-preview"
        - "gpt-4"
        - "gpt-3.5-turbo"
        - "gpt-3.5-turbo-16k"
      
  # AWS Bedrock configuration
  bedrock:
    enabled: true
    # Use IAM role credentials (no API key needed if running on AWS)
    # Or users can provide AWS credentials in UI
    apiKey: "${AWS_BEDROCK_API_KEY:user_provided}"
    region: "${AWS_BEDROCK_REGION:us-east-1}"
    models:
      default:
        - "anthropic.claude-3-opus-20240229"
        - "anthropic.claude-3-sonnet-20240229"
        - "anthropic.claude-3-haiku-20240307"
        - "anthropic.claude-instant-v1"
        - "amazon.titan-text-express-v1"
        - "ai21.j2-ultra-v1"
        - "ai21.j2-mid-v1"
        - "cohere.command-text-v14"
        - "meta.llama2-70b-chat-v1"
      
  # Anthropic configuration  
  anthropic:
    apiKey: "user_provided"
    models:
      default: 
        - "claude-3-opus-20240229"
        - "claude-3-sonnet-20240229"
        - "claude-3-haiku-20240307"
        - "claude-2.1"
        - "claude-instant-1.2"
      
  # Google configuration
  google:
    apiKey: "user_provided"
    models:
      default: 
        - "gemini-pro"
        - "gemini-pro-vision"
        
  # Azure OpenAI configuration (optional)
  azureOpenAI:
    apiKey: "user_provided"
    instanceName: "user_provided"
    apiVersion: "2024-02-15-preview"
    models:
      default:
        - "gpt-4-turbo"
        - "gpt-4"
        - "gpt-35-turbo"
        
  custom:
    # MCP Tools Server integration
    - name: "MCP Tools Server"
      apiKey: "not_required"
      baseURL: "http://localhost:3002"
      models:
        default: ["mcp-tools"]
      fetch: false
      
    # MCP Feedback Server integration  
    - name: "MCP Feedback Server"
      apiKey: "not_required"
      baseURL: "http://localhost:3003"
      models:
        default: ["mcp-feedback"]
      fetch: false